### PR TITLE
Added taptic success feedback when conversion is finished

### PR DESCRIPTION
**Pull request by mcblooder**
Added taptic success feedback when conversion is finished and also I allowed downloads using http protocol. I can exlude this change from PR, but to me it seems unreasonable to prevent user from using non-SSL servers to fetch videos.

### CODE REVIEW

**Comment by aheze** [comment]
Thanks! Apple doesn't allow downloads via http in published apps though. I'll remove it for you.

**Comment by mcblooder** [comment]
Oh, can you please provide link to rules where it says that you cannot use it. I have an application in store with it, and I just double checked on apple
forum they say it’s fine. Thank you :)

**Comment by aheze** [comment]
Here's an [old article](https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/)... but I think you're right. The [documentation](https://developer.apple.com/documentation/security/preventing_insecure_network_connections) says
> you can add exceptions to loosen some of the ATS requirements.

But it still seems scary:
> requires you to provide justification, and might trigger additional App Store review for your app.

**Comment by mcblooder** [comment]
Now when I think about it, almost every app that
I ever published had that option enabled for
some reason: fetching images, files
and e.t.c. No issues so far. Anyway is up to
you. Best of luck :)

**Comment by aheze** [comment]
Good to know. Thanks, you too!

**Pull request merged**
